//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class anexo
    {
        public int consecutivo { get; set; }
        public int id_registro_carpetas { get; set; }
        public string asunto { get; set; }
        public Nullable<System.DateTime> fgraba { get; set; }
        public Nullable<int> n_folios { get; set; }
    
        public virtual registro_carpetas registro_carpetas { get; set; }
    }
}
