//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class anotaciones
    {
        public int id_anotacion { get; set; }
        public int tipo_correspondencia { get; set; }
        public int id_correspondencia { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_dependencia { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public string login { get; set; }
        public string envia { get; set; }
    
        public virtual dependencias dependencias { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
