//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class archivo
    {
        public int id_archivo { get; set; }
        public Nullable<int> id_unidad_conservacion { get; set; }
        public Nullable<int> id_padre { get; set; }
        public Nullable<int> estado { get; set; }
        public string archivo1 { get; set; }
        public Nullable<int> id_flujo { get; set; }
        public Nullable<int> id_doc { get; set; }
        public Nullable<int> id_serie { get; set; }
        public Nullable<int> id_dependencia { get; set; }
        public Nullable<System.DateTime> finicial { get; set; }
        public Nullable<System.DateTime> ffinal { get; set; }
        public Nullable<int> folios { get; set; }
        public string nombre { get; set; }
        public string campo_ocr { get; set; }
        public string login { get; set; }
        public Nullable<int> imagenes { get; set; }
        public Nullable<System.DateTime> fgraba { get; set; }
        public string archivo_procedente { get; set; }
        public string archivo_actual { get; set; }
        public string transferido { get; set; }
        public Nullable<int> id_corr { get; set; }
        public Nullable<int> tipo_corr { get; set; }
        public string consultar { get; set; }
        public string administrar { get; set; }
        public string registrar { get; set; }
        public string transferir { get; set; }
        public string enviar { get; set; }
        public string imprimir { get; set; }
        public string guardar { get; set; }
        public Nullable<int> longitud { get; set; }
        public string ext { get; set; }
        public string ruta_imagen { get; set; }
        public string encriptada { get; set; }
        public Nullable<System.DateTime> fmodifica { get; set; }
        public Nullable<int> id_archivo_actual { get; set; }
    }
}
