//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class asunto
    {
        public int id_asunto { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> tiempo_central { get; set; }
        public Nullable<int> conservacion_total { get; set; }
        public Nullable<int> micro_digitaliza { get; set; }
        public Nullable<int> seleccion { get; set; }
        public Nullable<int> eliminacion { get; set; }
        public string procedimiento { get; set; }
        public Nullable<int> papel { get; set; }
        public Nullable<int> electronico { get; set; }
    }
}
