//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class campo_carpeta
    {
        public campo_carpeta()
        {
            this.campo_carpeta_indices = new HashSet<campo_carpeta_indices>();
        }
    
        public int id_campo { get; set; }
        public Nullable<int> id_registro_carpetas { get; set; }
        public string campo { get; set; }
        public Nullable<System.DateTime> fgraba { get; set; }
        public string carpeta { get; set; }
        public Nullable<int> folios { get; set; }
        public byte[] imagen { get; set; }
        public string archivo { get; set; }
    
        public virtual ICollection<campo_carpeta_indices> campo_carpeta_indices { get; set; }
        public virtual registro_carpetas registro_carpetas { get; set; }
    }
}
