//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class campo_inventario
    {
        public campo_inventario()
        {
            this.campo_indices = new HashSet<campo_indices>();
        }
    
        public int id_campo { get; set; }
        public Nullable<int> id_inventario { get; set; }
        public string campo { get; set; }
        public Nullable<System.DateTime> fgraba { get; set; }
        public string carpeta { get; set; }
        public Nullable<int> folios { get; set; }
        public Nullable<int> id_corr { get; set; }
        public Nullable<int> tipo_corr { get; set; }
        public byte[] imagen { get; set; }
        public string archivo { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual ICollection<campo_indices> campo_indices { get; set; }
        public virtual inventario_documental inventario_documental { get; set; }
    }
}
