//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargos
    {
        public cargos()
        {
            this.dependencias = new HashSet<dependencias>();
        }
    
        public int id_cargos { get; set; }
        public string nombre { get; set; }
        public string observaciones { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<dependencias> dependencias { get; set; }
    }
}
