//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cob_sede_cont_courier
    {
        public int id_cob_sede_cont_courier { get; set; }
        public Nullable<int> id_sede_contrato_courier { get; set; }
        public string id_ciudad { get; set; }
        public Nullable<int> id_tipo_trayecto { get; set; }
        public string observaciones { get; set; }
        public string estado { get; set; }
    }
}
