//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class control_respuestas
    {
        public int id_control { get; set; }
        public Nullable<int> id_recibida { get; set; }
        public string login { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual recibida recibida { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
