//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class copia_seguridad
    {
        public int id_copia { get; set; }
        public Nullable<int> id_registro { get; set; }
        public string tipo { get; set; }
        public string codigo { get; set; }
        public string cd { get; set; }
        public string archivo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public Nullable<int> tamano { get; set; }
        public string login { get; set; }
        public string carpeta { get; set; }
        public Nullable<int> id_carpeta { get; set; }
        public Nullable<System.DateTime> fechai { get; set; }
        public Nullable<System.DateTime> fechah { get; set; }
    }
}
