//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class dependencias
    {
        public dependencias()
        {
            this.anotaciones = new HashSet<anotaciones>();
            this.categorias = new HashSet<categorias>();
            this.despachada_dependencias = new HashSet<despachada_dependencias>();
            this.interna_dependencias = new HashSet<interna_dependencias>();
            this.inventario_documental = new HashSet<inventario_documental>();
            this.plantilla = new HashSet<plantilla>();
            this.recibida_dependencias = new HashSet<recibida_dependencias>();
            this.tabla_retencion = new HashSet<tabla_retencion>();
            this.usuarios_serie = new HashSet<usuarios_serie>();
            this.usuarios = new HashSet<usuarios>();
            this.usuarios1 = new HashSet<usuarios>();
        }
    
        public int id_dependencia { get; set; }
        public string nombre { get; set; }
        public int id_cargos { get; set; }
        public string codigo { get; set; }
        public int id_sede { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<anotaciones> anotaciones { get; set; }
        public virtual cargos cargos { get; set; }
        public virtual ICollection<categorias> categorias { get; set; }
        public virtual sedes sedes { get; set; }
        public virtual ICollection<despachada_dependencias> despachada_dependencias { get; set; }
        public virtual ICollection<interna_dependencias> interna_dependencias { get; set; }
        public virtual ICollection<inventario_documental> inventario_documental { get; set; }
        public virtual ICollection<plantilla> plantilla { get; set; }
        public virtual ICollection<recibida_dependencias> recibida_dependencias { get; set; }
        public virtual ICollection<tabla_retencion> tabla_retencion { get; set; }
        public virtual ICollection<usuarios_serie> usuarios_serie { get; set; }
        public virtual ICollection<usuarios> usuarios { get; set; }
        public virtual ICollection<usuarios> usuarios1 { get; set; }
    }
}
