//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class dependencia
    {
        public int id_dependencia { get; set; }
        public string archivo_actual { get; set; }
        public string consultar { get; set; }
        public string registrar { get; set; }
        public string administrar { get; set; }
        public string guardar { get; set; }
        public string imprimir { get; set; }
        public string enviar { get; set; }
        public string transferir { get; set; }
    }
}
