//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class despachada
    {
        public despachada()
        {
            this.despachada_dependencias = new HashSet<despachada_dependencias>();
            this.despachada_indices = new HashSet<despachada_indices>();
            this.respuesta_tramite = new HashSet<respuesta_tramite>();
        }
    
        public int id_despachada { get; set; }
        public int consecutivo_gral { get; set; }
        public Nullable<int> consecutivo_fax { get; set; }
        public Nullable<int> consecutivo_email { get; set; }
        public int temporada { get; set; }
        public Nullable<System.DateTime> fgraba { get; set; }
        public string noguia { get; set; }
        public string envia { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string id_documento { get; set; }
        public int id_tiposenvio { get; set; }
        public string enviado_por { get; set; }
        public string destinatario { get; set; }
        public string resumen { get; set; }
        public string usuario_grabo { get; set; }
        public string cd { get; set; }
        public string sizea { get; set; }
        public string id_ciudad { get; set; }
        public string login { get; set; }
        public Nullable<System.DateTime> fradica { get; set; }
        public string hradica { get; set; }
        public Nullable<int> id_recibida { get; set; }
        public Nullable<int> id_serie { get; set; }
        public Nullable<int> id_dependencia { get; set; }
        public Nullable<int> n_folios { get; set; }
        public byte[] imagen { get; set; }
        public Nullable<int> id_sede { get; set; }
        public Nullable<int> id_mensajero { get; set; }
        public Nullable<int> id_sede_envia { get; set; }
        public Nullable<int> estado { get; set; }
        public string archivo { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> imagenes { get; set; }
        public Nullable<int> longitud { get; set; }
        public string ext { get; set; }
        public string tipo_documento { get; set; }
        public Nullable<int> id_flujo { get; set; }
        public string referencia { get; set; }
        public Nullable<long> valor_declarado { get; set; }
        public string estado_uso { get; set; }
        public string contenido { get; set; }
        public string estado_envio { get; set; }
        public Nullable<int> id_dependencia_radicacion { get; set; }
        public string ruta_imagen { get; set; }
        public string encriptada { get; set; }
    
        public virtual ICollection<despachada_dependencias> despachada_dependencias { get; set; }
        public virtual ICollection<despachada_indices> despachada_indices { get; set; }
        public virtual temporadas temporadas { get; set; }
        public virtual ICollection<respuesta_tramite> respuesta_tramite { get; set; }
    }
}
