//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class despachada_masiva
    {
        public int id_despachada_masiva { get; set; }
        public Nullable<int> numero { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_sede { get; set; }
        public Nullable<int> id_dependencia { get; set; }
        public string login { get; set; }
        public string estado { get; set; }
        public string observaciones { get; set; }
        public string log_errores { get; set; }
    }
}
