//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class despachada_dependencias
    {
        public int id_dependencia { get; set; }
        public int id_despachada { get; set; }
        public string login { get; set; }
        public Nullable<int> id_anotacion { get; set; }
    
        public virtual dependencias dependencias { get; set; }
        public virtual despachada despachada { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
