//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class destinatario_externo
    {
        public int id_despachada { get; set; }
        public int item { get; set; }
        public string original { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public string cednit { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string telefono_fijo { get; set; }
        public string telefono_celular { get; set; }
        public string ciudad { get; set; }
        public string email { get; set; }
        public string observaciones { get; set; }
        public string referencia { get; set; }
        public string estado_telemercadeo { get; set; }
        public Nullable<int> ubicacion_fisica { get; set; }
        public string estado_ubicacion { get; set; }
        public Nullable<int> id_courier { get; set; }
        public Nullable<long> consecutivo_envio { get; set; }
        public string nombre_courier { get; set; }
        public string guia { get; set; }
        public string tipo_estado { get; set; }
        public string id_estado_despacho { get; set; }
        public Nullable<double> peso_neto { get; set; }
        public Nullable<long> valor_despacho { get; set; }
        public Nullable<System.DateTime> fecha_envio_guia { get; set; }
        public string hora_envio_guia { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public string hora_recepcion { get; set; }
        public Nullable<int> id_tipo_identificacion { get; set; }
    }
}
