//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos_especiales_indices
    {
        public documentos_especiales_indices()
        {
            this.campo_carpeta_indices = new HashSet<campo_carpeta_indices>();
            this.campo_indices = new HashSet<campo_indices>();
            this.despachada_indices = new HashSet<despachada_indices>();
            this.interna_indices = new HashSet<interna_indices>();
            this.inventario_indices = new HashSet<inventario_indices>();
            this.recibida_indices = new HashSet<recibida_indices>();
            this.registro_carpetas_indices = new HashSet<registro_carpetas_indices>();
        }
    
        public int id_indice { get; set; }
        public Nullable<int> id_doce { get; set; }
        public string nombre_indice { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<int> seleccion { get; set; }
        public Nullable<int> posicion { get; set; }
    
        public virtual ICollection<campo_carpeta_indices> campo_carpeta_indices { get; set; }
        public virtual ICollection<campo_indices> campo_indices { get; set; }
        public virtual ICollection<despachada_indices> despachada_indices { get; set; }
        public virtual documentos_especiales documentos_especiales { get; set; }
        public virtual ICollection<interna_indices> interna_indices { get; set; }
        public virtual ICollection<inventario_indices> inventario_indices { get; set; }
        public virtual ICollection<recibida_indices> recibida_indices { get; set; }
        public virtual ICollection<registro_carpetas_indices> registro_carpetas_indices { get; set; }
    }
}
