//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento_adjunto
    {
        public int id { get; set; }
        public Nullable<int> id_tipo_modulo { get; set; }
        public Nullable<int> id_identificador { get; set; }
        public Nullable<int> id_doc { get; set; }
    }
}
