//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos_especiales
    {
        public documentos_especiales()
        {
            this.documentos_especiales_indices = new HashSet<documentos_especiales_indices>();
        }
    
        public int id_doce { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string tipo { get; set; }
        public Nullable<int> estado { get; set; }
        public string permisos_grupo { get; set; }
    
        public virtual ICollection<documentos_especiales_indices> documentos_especiales_indices { get; set; }
    }
}
