//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        public int id_documento { get; set; }
        public byte[] imagen { get; set; }
        public Nullable<int> id_flujo { get; set; }
        public Nullable<int> id_doc { get; set; }
        public Nullable<int> estado { get; set; }
        public string archivo { get; set; }
        public Nullable<System.DateTime> fgraba { get; set; }
        public Nullable<int> id_doce { get; set; }
    }
}
