//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class fax_settings
    {
        public int id_n { get; set; }
        public string pathrecibidos { get; set; }
        public string pathenviados { get; set; }
        public string pathtmp { get; set; }
        public string pathconvertidos { get; set; }
        public string pathpidefaxsnd { get; set; }
        public Nullable<int> timecheckpendientes { get; set; }
    }
}
