//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class flujo_permi_correspondencia
    {
        public int id_tipo { get; set; }
        public Nullable<int> recibida { get; set; }
        public Nullable<int> interna { get; set; }
        public Nullable<int> despachada { get; set; }
    
        public virtual flujo_tipo flujo_tipo { get; set; }
    }
}
