//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class flujo_responsables
    {
        public flujo_responsables()
        {
            this.flujo_actividad = new HashSet<flujo_actividad>();
            this.flujo_paso = new HashSet<flujo_paso>();
            this.flujo_tipo = new HashSet<flujo_tipo>();
        }
    
        public string login { get; set; }
        public string activo { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual ICollection<flujo_actividad> flujo_actividad { get; set; }
        public virtual ICollection<flujo_paso> flujo_paso { get; set; }
        public virtual ICollection<flujo_tipo> flujo_tipo { get; set; }
    }
}
