//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class flujo_matriz_paso
    {
        public int id_matriz { get; set; }
        public Nullable<int> id_paso1 { get; set; }
        public Nullable<int> id_paso2 { get; set; }
        public Nullable<int> id_estado { get; set; }
    }
}
