//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class flujo_act_estado
    {
        public int id_act_estado { get; set; }
        public int id_actividad { get; set; }
        public int id_flujo { get; set; }
        public string login { get; set; }
        public Nullable<int> id_estado { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public Nullable<int> finalizado { get; set; }
        public Nullable<System.DateTime> fecha_ini { get; set; }
        public string hora_ini { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string hora_fin { get; set; }
        public Nullable<int> pasos { get; set; }
        public Nullable<short> cambio_resp { get; set; }
        public string documento_relacionado { get; set; }
        public string detalle { get; set; }
        public string documento_relacionado_previo { get; set; }
    
        public virtual flujo flujo { get; set; }
        public virtual flujo_actividad flujo_actividad { get; set; }
    }
}
