//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class flujo_seguimiento_paso
    {
        public int id_seguimiento { get; set; }
        public int id_paso { get; set; }
        public int id_flujo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public string observacion { get; set; }
    
        public virtual flujo flujo { get; set; }
        public virtual flujo_paso flujo_paso { get; set; }
    }
}
