//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class flujo_tipo
    {
        public flujo_tipo()
        {
            this.flujo = new HashSet<flujo>();
            this.flujo_actividad = new HashSet<flujo_actividad>();
            this.flujo_doc = new HashSet<flujo_doc>();
            this.flujo_estado = new HashSet<flujo_estado>();
            this.flujo_permi_responsables = new HashSet<flujo_permi_responsables>();
            this.flujo_responsables = new HashSet<flujo_responsables>();
        }
    
        public int id_tipo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string documentos { get; set; }
        public string requisitos { get; set; }
        public Nullable<int> archivar { get; set; }
    
        public virtual ICollection<flujo> flujo { get; set; }
        public virtual ICollection<flujo_actividad> flujo_actividad { get; set; }
        public virtual ICollection<flujo_doc> flujo_doc { get; set; }
        public virtual ICollection<flujo_estado> flujo_estado { get; set; }
        public virtual flujo_permi_correspondencia flujo_permi_correspondencia { get; set; }
        public virtual flujo_permi_plantilla flujo_permi_plantilla { get; set; }
        public virtual ICollection<flujo_permi_responsables> flujo_permi_responsables { get; set; }
        public virtual ICollection<flujo_responsables> flujo_responsables { get; set; }
    }
}
