//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class flujo_paso_estado
    {
        public int id_paso_estado { get; set; }
        public int id_paso { get; set; }
        public int id_flujo { get; set; }
        public string login { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public Nullable<int> finalizado { get; set; }
        public Nullable<System.DateTime> fecha_ini { get; set; }
        public string hora_ini { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string hora_fin { get; set; }
        public Nullable<int> cambio_resp { get; set; }
    
        public virtual flujo flujo { get; set; }
        public virtual flujo_paso flujo_paso { get; set; }
    }
}
