//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class flujo_actividad
    {
        public flujo_actividad()
        {
            this.flujo_act_estado = new HashSet<flujo_act_estado>();
            this.flujo_paso = new HashSet<flujo_paso>();
            this.flujo_seguimiento = new HashSet<flujo_seguimiento>();
            this.flujo_responsables = new HashSet<flujo_responsables>();
        }
    
        public int id_actividad { get; set; }
        public int id_tipo { get; set; }
        public string nombre_act { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> duracion { get; set; }
        public Nullable<int> posicion { get; set; }
        public Nullable<int> tipo_dura { get; set; }
        public Nullable<int> tipo { get; set; }
    
        public virtual ICollection<flujo_act_estado> flujo_act_estado { get; set; }
        public virtual flujo_tipo flujo_tipo { get; set; }
        public virtual ICollection<flujo_paso> flujo_paso { get; set; }
        public virtual ICollection<flujo_seguimiento> flujo_seguimiento { get; set; }
        public virtual ICollection<flujo_responsables> flujo_responsables { get; set; }
    }
}
