//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class flujo_doc
    {
        public int id_doc { get; set; }
        public string nombre_doc { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public string login { get; set; }
        public Nullable<int> id_flujo { get; set; }
        public Nullable<int> temporada { get; set; }
        public Nullable<int> id_tipo { get; set; }
        public string carpeta { get; set; }
        public string tipo_correspondencia { get; set; }
        public string consecutivo_corr { get; set; }
        public string coddependencia { get; set; }
        public Nullable<int> id_actividad { get; set; }
        public Nullable<int> id_paso { get; set; }
        public Nullable<int> longitud { get; set; }
        public string ruta_adjunto { get; set; }
        public Nullable<int> archivo_oid { get; set; }
    
        public virtual flujo flujo { get; set; }
        public virtual flujo_tipo flujo_tipo { get; set; }
    }
}
