//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class guia_asignada
    {
        public int id_guia_asignada { get; set; }
        public Nullable<int> id_rango_guia { get; set; }
        public string prefijo { get; set; }
        public Nullable<int> guia { get; set; }
        public string tipo_comunicacion { get; set; }
        public Nullable<int> id_planilla { get; set; }
    }
}
