//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_int_dependencias
    {
        public int id_interna { get; set; }
        public int id_dependencia { get; set; }
        public string login { get; set; }
        public int secuencia { get; set; }
        public string original { get; set; }
    }
}
