//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_resp_tramite_int
    {
        public int id_respuesta { get; set; }
        public int secuencia { get; set; }
        public Nullable<int> id_interna_recibe { get; set; }
        public Nullable<int> id_interna_despacha { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
