//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_interna
    {
        public int id_interna { get; set; }
        public int secuencia { get; set; }
        public Nullable<System.DateTime> fecha_historial { get; set; }
        public string hora_historial { get; set; }
        public string login_historial { get; set; }
        public string tipo_login { get; set; }
        public int temporada { get; set; }
        public int consecutivo { get; set; }
        public Nullable<System.DateTime> fgraba { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string origen { get; set; }
        public string id_documento { get; set; }
        public Nullable<int> estado_tramite { get; set; }
        public string resumen { get; set; }
        public string login { get; set; }
        public string usuario_grabo { get; set; }
        public Nullable<int> id_tramite { get; set; }
        public string cd { get; set; }
        public Nullable<int> sizea { get; set; }
        public Nullable<System.DateTime> fradica { get; set; }
        public string hradica { get; set; }
        public Nullable<int> id_flujo { get; set; }
        public Nullable<int> id_doc { get; set; }
        public Nullable<int> id_recibida { get; set; }
        public Nullable<int> id_serie { get; set; }
        public Nullable<int> id_dependencia { get; set; }
        public Nullable<int> n_folios { get; set; }
        public string imagen { get; set; }
        public Nullable<int> id_sede { get; set; }
        public Nullable<int> id_mensajero { get; set; }
        public Nullable<int> id_sede_envia { get; set; }
        public Nullable<int> estado { get; set; }
        public string archivo { get; set; }
        public Nullable<int> imagenes { get; set; }
        public string responsable { get; set; }
        public string ext { get; set; }
        public Nullable<int> longitud { get; set; }
        public Nullable<int> id_archivo { get; set; }
        public Nullable<System.DateTime> fmodifica { get; set; }
        public Nullable<int> id_dependencia_radicacion { get; set; }
    }
}
