//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class interna_plantilla
    {
        public int id_interna { get; set; }
        public Nullable<int> id_plantilla { get; set; }
        public Nullable<int> id_recibida { get; set; }
        public Nullable<int> diligencia { get; set; }
        public Nullable<int> temporada { get; set; }
        public Nullable<int> consecutivo { get; set; }
    }
}
