//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class interna_remitente
    {
        public int id_interna { get; set; }
        public string login { get; set; }
        public int version_borrador { get; set; }
        public Nullable<int> item { get; set; }
        public Nullable<int> id_dependencia { get; set; }
        public string propietario { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public string observacion { get; set; }
        public string visible { get; set; }
    }
}
