//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario_documental
    {
        public inventario_documental()
        {
            this.campo_inventario = new HashSet<campo_inventario>();
            this.inventario_indices = new HashSet<inventario_indices>();
        }
    
        public int id_inventario { get; set; }
        public Nullable<int> id_seriedocumental { get; set; }
        public Nullable<int> id_dependencia { get; set; }
        public string orden { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> f_inicial { get; set; }
        public Nullable<System.DateTime> f_final { get; set; }
        public string unidad_conservacion { get; set; }
        public Nullable<int> n_folios { get; set; }
        public string ubicacion { get; set; }
        public string notas { get; set; }
        public string carpeta { get; set; }
        public Nullable<int> transferido { get; set; }
        public string deposito { get; set; }
        public string gaveta { get; set; }
        public string bandeja { get; set; }
        public string caja_estante { get; set; }
        public string caja { get; set; }
        public Nullable<int> rango1 { get; set; }
        public Nullable<int> rango2 { get; set; }
        public Nullable<System.DateTime> fgraba { get; set; }
        public string cor { get; set; }
    
        public virtual ICollection<campo_inventario> campo_inventario { get; set; }
        public virtual dependencias dependencias { get; set; }
        public virtual ICollection<inventario_indices> inventario_indices { get; set; }
        public virtual serie_documental serie_documental { get; set; }
    }
}
