//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_clasificacion_despachada
    {
        public int id_clasificacion_despachada { get; set; }
        public int item { get; set; }
        public Nullable<int> id_despachada { get; set; }
        public Nullable<int> item_despachada { get; set; }
        public Nullable<int> id_contrato_courier { get; set; }
        public Nullable<int> id_servicio_mensajeria { get; set; }
        public Nullable<int> carta_porte { get; set; }
        public Nullable<double> peso { get; set; }
        public string observaciones { get; set; }
        public string estado_registro { get; set; }
        public string estado_ubicacion { get; set; }
    }
}
