//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.opcion = new HashSet<opcion>();
        }
    
        public int id_item { get; set; }
        public Nullable<int> id_plantilla { get; set; }
        public Nullable<int> tipo { get; set; }
        public string titulo { get; set; }
        public Nullable<int> seleccion { get; set; }
        public string nbd { get; set; }
        public Nullable<int> posicion { get; set; }
    
        public virtual plantilla plantilla { get; set; }
        public virtual ICollection<opcion> opcion { get; set; }
    }
}
