//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_despachada_masiva
    {
        public int id_despachada_masiva { get; set; }
        public int item { get; set; }
        public string sede_plano { get; set; }
        public Nullable<int> id_sede { get; set; }
        public string dependencia_plano { get; set; }
        public Nullable<int> id_dependencia { get; set; }
        public string remitente_plano { get; set; }
        public string remitente { get; set; }
        public string tipo_documento_plano { get; set; }
        public string tipo_documento { get; set; }
        public string fecha_documento_plano { get; set; }
        public Nullable<System.DateTime> fecha_documento { get; set; }
        public string resumen_plano { get; set; }
        public string resumen { get; set; }
        public string original_plano { get; set; }
        public string original { get; set; }
        public string nombre_destinatario_plano { get; set; }
        public string nombre_destinatario { get; set; }
        public string documento_destinatario_plano { get; set; }
        public string documento_destinatario { get; set; }
        public string direccion_plano { get; set; }
        public string direccion { get; set; }
        public string telefono_fijo_plano { get; set; }
        public string telefono_fijo { get; set; }
        public string telefono_celular_plano { get; set; }
        public string telefono_celular { get; set; }
        public string ciudad_plano { get; set; }
        public string id_ciudad { get; set; }
        public string departamento_plano { get; set; }
        public string id_departamento { get; set; }
        public string email_plano { get; set; }
        public string email { get; set; }
        public string referencia_destinatario_plano { get; set; }
        public string referencia_destinatario { get; set; }
        public string guia_plano { get; set; }
        public string guia { get; set; }
        public string destinatarios_internos_plano { get; set; }
        public string destinatarios_internos { get; set; }
        public string consecutivo_radicacion_plano { get; set; }
        public Nullable<int> consecutivo_radicacion { get; set; }
        public string sede_radicacion_plano { get; set; }
        public Nullable<int> sede_radicacion { get; set; }
        public string temporada_radicacion_plano { get; set; }
        public Nullable<int> temporada_radicacion { get; set; }
        public Nullable<int> id_recibida { get; set; }
        public string nombre_tramite_plano { get; set; }
        public string nombre_tramite { get; set; }
        public string numero_tramite_plano { get; set; }
        public Nullable<int> numero_tramite { get; set; }
        public Nullable<int> id_tramite { get; set; }
        public string mensajero_plano { get; set; }
        public string mensajero { get; set; }
        public Nullable<int> id_mensajero { get; set; }
        public string serie_documental_plano { get; set; }
        public Nullable<int> serie_documental { get; set; }
        public string dependencia_serie_docu_plano { get; set; }
        public Nullable<int> id_dependencia_serie_docu { get; set; }
        public Nullable<int> id_tabla_retencion { get; set; }
        public string referencia_plano { get; set; }
        public string referencia { get; set; }
        public string folios_plano { get; set; }
        public Nullable<int> folios { get; set; }
        public string valor_declarado_plano { get; set; }
        public Nullable<long> valor_declarado { get; set; }
        public string estado_uso_plano { get; set; }
        public string estado_uso { get; set; }
        public string contenido_plano { get; set; }
        public string contenido { get; set; }
        public string observaciones_plano { get; set; }
        public string observaciones { get; set; }
        public string extras { get; set; }
        public string estado_registro { get; set; }
        public Nullable<int> id_despachada { get; set; }
        public Nullable<int> item_despachada { get; set; }
        public string tipo_envio_plano { get; set; }
        public string tipo_envio { get; set; }
        public Nullable<int> id_tiposenvio { get; set; }
        public string descripcion_estado_registro { get; set; }
    }
}
