//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_notificacion
    {
        public int id_notificacion { get; set; }
        public string login { get; set; }
        public string email_notificado { get; set; }
        public string estado { get; set; }
    
        public virtual notificacion notificacion { get; set; }
    }
}
