//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_registro_estado_despacha
    {
        public int id_registro_estado_despacha { get; set; }
        public int item { get; set; }
        public Nullable<int> id_courier { get; set; }
        public string consecutivo_envio_plano { get; set; }
        public Nullable<int> consecutivo_envio { get; set; }
        public string guia_plano { get; set; }
        public string guia { get; set; }
        public string fecha_despacho_plano { get; set; }
        public Nullable<System.DateTime> fecha_despacho { get; set; }
        public string hora_despacho_plano { get; set; }
        public string hora_despacho { get; set; }
        public string estado_despacho_plano { get; set; }
        public string id_estado_despacho { get; set; }
        public string valor_despacho_plano { get; set; }
        public Nullable<long> valor_despacho { get; set; }
        public string fecha_recepcion_plano { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public string hora_recepcion_plano { get; set; }
        public string hora_recepcion { get; set; }
        public string observaciones_devolucion { get; set; }
        public string estado_registro { get; set; }
        public Nullable<int> orden_modificacion_estado { get; set; }
        public string descripcion_estado_registro { get; set; }
    }
}
