//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_planilla_electro_externa
    {
        public int id_planilla_electro_externa { get; set; }
        public int item { get; set; }
        public Nullable<int> id_courier { get; set; }
        public Nullable<long> consecutivo_envio { get; set; }
        public Nullable<int> id_servicio_mensajeria { get; set; }
        public Nullable<int> id_elemento { get; set; }
        public Nullable<int> item_elemento { get; set; }
        public string descripcion { get; set; }
        public string observaciones_envio { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public string telefono { get; set; }
        public string observaciones_recepcion { get; set; }
        public string guia { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public string hora_recepcion { get; set; }
        public string estado { get; set; }
        public string id_estado_despacho { get; set; }
    }
}
