//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_planilla_electronica
    {
        public int id_planilla_electronica { get; set; }
        public int item { get; set; }
        public string tipo_elemento { get; set; }
        public Nullable<int> id_elemento { get; set; }
        public Nullable<int> item_elemento { get; set; }
        public string descripcion { get; set; }
        public string observaciones_envio { get; set; }
        public string observaciones_recepcion { get; set; }
        public string estado { get; set; }
    }
}
