//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_inventario
    {
        public item_inventario()
        {
            this.opcion_inventario = new HashSet<opcion_inventario>();
        }
    
        public int id_item { get; set; }
        public int id_plantilla { get; set; }
        public Nullable<int> tipo { get; set; }
        public string titulo { get; set; }
        public Nullable<int> seleccion { get; set; }
        public string nbd { get; set; }
        public Nullable<int> posicion { get; set; }
    
        public virtual plantilla_inventario plantilla_inventario { get; set; }
        public virtual ICollection<opcion_inventario> opcion_inventario { get; set; }
    }
}
