//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_flujo_cargue_electro
    {
        public int id { get; set; }
        public int item { get; set; }
        public string referencia { get; set; }
        public Nullable<int> id_flujo_act_estado { get; set; }
        public string documento_relacionado { get; set; }
        public string estado { get; set; }
    }
}
