//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensajero
    {
        public int id_mensajero { get; set; }
        public string nombre { get; set; }
        public Nullable<int> cedula { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> id_sede { get; set; }
        public Nullable<int> id_courier { get; set; }
        public string estado { get; set; }
    }
}
