//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ficheroEntities : DbContext
    {
        public ficheroEntities()
            : base("name=ficheroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<administradores> administradores { get; set; }
        public DbSet<anexo> anexo { get; set; }
        public DbSet<anotaciones> anotaciones { get; set; }
        public DbSet<archivo> archivo { get; set; }
        public DbSet<archivo_indices> archivo_indices { get; set; }
        public DbSet<archivo_permisos> archivo_permisos { get; set; }
        public DbSet<asunto> asunto { get; set; }
        public DbSet<auditoria> auditoria { get; set; }
        public DbSet<campo_carpeta> campo_carpeta { get; set; }
        public DbSet<campo_carpeta_indices> campo_carpeta_indices { get; set; }
        public DbSet<campo_indices> campo_indices { get; set; }
        public DbSet<campo_inventario> campo_inventario { get; set; }
        public DbSet<cargos> cargos { get; set; }
        public DbSet<categorias> categorias { get; set; }
        public DbSet<categorias_usuarios> categorias_usuarios { get; set; }
        public DbSet<central_usuarios> central_usuarios { get; set; }
        public DbSet<ciudades> ciudades { get; set; }
        public DbSet<clasificacion_despachada> clasificacion_despachada { get; set; }
        public DbSet<cob_sede_cont_courier> cob_sede_cont_courier { get; set; }
        public DbSet<cobertura_courier> cobertura_courier { get; set; }
        public DbSet<contrato_courier> contrato_courier { get; set; }
        public DbSet<control_respuestas> control_respuestas { get; set; }
        public DbSet<copia_seguridad> copia_seguridad { get; set; }
        public DbSet<costo_serv_mensajeria> costo_serv_mensajeria { get; set; }
        public DbSet<courier> courier { get; set; }
        public DbSet<departamento> departamento { get; set; }
        public DbSet<dependencia> dependencia { get; set; }
        public DbSet<dependencias> dependencias { get; set; }
        public DbSet<despachada> despachada { get; set; }
        public DbSet<despachada_dependencias> despachada_dependencias { get; set; }
        public DbSet<despachada_historial> despachada_historial { get; set; }
        public DbSet<despachada_indices> despachada_indices { get; set; }
        public DbSet<despachada_masiva> despachada_masiva { get; set; }
        public DbSet<despachada_usuarios> despachada_usuarios { get; set; }
        public DbSet<destinatario_externo> destinatario_externo { get; set; }
        public DbSet<documento> documento { get; set; }
        public DbSet<documento_adjunto> documento_adjunto { get; set; }
        public DbSet<documento_indices> documento_indices { get; set; }
        public DbSet<documento_pto_usuarios> documento_pto_usuarios { get; set; }
        public DbSet<documento_usuarios> documento_usuarios { get; set; }
        public DbSet<documentos_especiales> documentos_especiales { get; set; }
        public DbSet<documentos_especiales_indices> documentos_especiales_indices { get; set; }
        public DbSet<entidades> entidades { get; set; }
        public DbSet<estado_despacho> estado_despacho { get; set; }
        public DbSet<evento> evento { get; set; }
        public DbSet<fax_settings> fax_settings { get; set; }
        public DbSet<flujo> flujo { get; set; }
        public DbSet<flujo_act_estado> flujo_act_estado { get; set; }
        public DbSet<flujo_actividad> flujo_actividad { get; set; }
        public DbSet<flujo_calendario> flujo_calendario { get; set; }
        public DbSet<flujo_cancelado_observacion> flujo_cancelado_observacion { get; set; }
        public DbSet<flujo_cargue_electro> flujo_cargue_electro { get; set; }
        public DbSet<flujo_doc> flujo_doc { get; set; }
        public DbSet<flujo_estado> flujo_estado { get; set; }
        public DbSet<flujo_histo_resp> flujo_histo_resp { get; set; }
        public DbSet<flujo_horario> flujo_horario { get; set; }
        public DbSet<flujo_matriz_act> flujo_matriz_act { get; set; }
        public DbSet<flujo_matriz_paso> flujo_matriz_paso { get; set; }
        public DbSet<flujo_paso> flujo_paso { get; set; }
        public DbSet<flujo_paso_estado> flujo_paso_estado { get; set; }
        public DbSet<flujo_permi_correspondencia> flujo_permi_correspondencia { get; set; }
        public DbSet<flujo_permi_plantilla> flujo_permi_plantilla { get; set; }
        public DbSet<flujo_permi_responsables> flujo_permi_responsables { get; set; }
        public DbSet<flujo_permi_usuarios> flujo_permi_usuarios { get; set; }
        public DbSet<flujo_responsables> flujo_responsables { get; set; }
        public DbSet<flujo_seguimiento> flujo_seguimiento { get; set; }
        public DbSet<flujo_seguimiento_paso> flujo_seguimiento_paso { get; set; }
        public DbSet<flujo_temporada> flujo_temporada { get; set; }
        public DbSet<flujo_tipo> flujo_tipo { get; set; }
        public DbSet<grupos> grupos { get; set; }
        public DbSet<grupos_usuarios> grupos_usuarios { get; set; }
        public DbSet<guia_asignada> guia_asignada { get; set; }
        public DbSet<historial_desp_dependencias> historial_desp_dependencias { get; set; }
        public DbSet<historial_despachada> historial_despachada { get; set; }
        public DbSet<historial_despachada_indices> historial_despachada_indices { get; set; }
        public DbSet<historial_destinatario_externo> historial_destinatario_externo { get; set; }
        public DbSet<historial_int_dependencias> historial_int_dependencias { get; set; }
        public DbSet<historial_interna> historial_interna { get; set; }
        public DbSet<historial_interna_indices> historial_interna_indices { get; set; }
        public DbSet<historial_interna_plantilla> historial_interna_plantilla { get; set; }
        public DbSet<historial_interna_remitente> historial_interna_remitente { get; set; }
        public DbSet<historial_rec_dependencias> historial_rec_dependencias { get; set; }
        public DbSet<historial_recibida> historial_recibida { get; set; }
        public DbSet<historial_recibida_indices> historial_recibida_indices { get; set; }
        public DbSet<historial_resp_tramite_int> historial_resp_tramite_int { get; set; }
        public DbSet<historial_respuesta_corresp> historial_respuesta_corresp { get; set; }
        public DbSet<historial_respuesta_recibida> historial_respuesta_recibida { get; set; }
        public DbSet<historial_respuesta_tramite> historial_respuesta_tramite { get; set; }
        public DbSet<interna> interna { get; set; }
        public DbSet<interna_adjunto> interna_adjunto { get; set; }
        public DbSet<interna_dependencias> interna_dependencias { get; set; }
        public DbSet<interna_historial> interna_historial { get; set; }
        public DbSet<interna_indices> interna_indices { get; set; }
        public DbSet<interna_plantilla> interna_plantilla { get; set; }
        public DbSet<interna_remitente> interna_remitente { get; set; }
        public DbSet<interna_usuarios> interna_usuarios { get; set; }
        public DbSet<inventario_documental> inventario_documental { get; set; }
        public DbSet<inventario_indices> inventario_indices { get; set; }
        public DbSet<item> item { get; set; }
        public DbSet<item_clasificacion_despachada> item_clasificacion_despachada { get; set; }
        public DbSet<item_despachada_masiva> item_despachada_masiva { get; set; }
        public DbSet<item_evento> item_evento { get; set; }
        public DbSet<item_flujo_cargue_electro> item_flujo_cargue_electro { get; set; }
        public DbSet<item_guia_despachada> item_guia_despachada { get; set; }
        public DbSet<item_imagen_guia_despachada> item_imagen_guia_despachada { get; set; }
        public DbSet<item_interna> item_interna { get; set; }
        public DbSet<item_inventario> item_inventario { get; set; }
        public DbSet<item_notificacion> item_notificacion { get; set; }
        public DbSet<item_planilla_electro_externa> item_planilla_electro_externa { get; set; }
        public DbSet<item_planilla_electronica> item_planilla_electronica { get; set; }
        public DbSet<item_registro_estado_despacha> item_registro_estado_despacha { get; set; }
        public DbSet<libro_firma> libro_firma { get; set; }
        public DbSet<log_consulta> log_consulta { get; set; }
        public DbSet<log_usuarios> log_usuarios { get; set; }
        public DbSet<mensajero> mensajero { get; set; }
        public DbSet<modu> modu { get; set; }
        public DbSet<notifica_cambio_rble_wf> notifica_cambio_rble_wf { get; set; }
        public DbSet<notificacion> notificacion { get; set; }
        public DbSet<notificacion_correspondencia> notificacion_correspondencia { get; set; }
        public DbSet<opcion> opcion { get; set; }
        public DbSet<opcion_indice> opcion_indice { get; set; }
        public DbSet<opcion_interna> opcion_interna { get; set; }
        public DbSet<opcion_inventario> opcion_inventario { get; set; }
        public DbSet<opciones_fecha_vencimiento> opciones_fecha_vencimiento { get; set; }
        public DbSet<parametros_generales> parametros_generales { get; set; }
        public DbSet<perfil_campo> perfil_campo { get; set; }
        public DbSet<perfil_usuario> perfil_usuario { get; set; }
        public DbSet<perfiles_vista> perfiles_vista { get; set; }
        public DbSet<permisos_correspondencias> permisos_correspondencias { get; set; }
        public DbSet<permisos_planilla_electronica> permisos_planilla_electronica { get; set; }
        public DbSet<planilla_electro_externa> planilla_electro_externa { get; set; }
        public DbSet<planilla_electronica> planilla_electronica { get; set; }
        public DbSet<plantilla> plantilla { get; set; }
        public DbSet<plantilla_interna> plantilla_interna { get; set; }
        public DbSet<plantilla_inventario> plantilla_inventario { get; set; }
        public DbSet<plantilla_inventario_usuarios> plantilla_inventario_usuarios { get; set; }
        public DbSet<plantilla_usuarios> plantilla_usuarios { get; set; }
        public DbSet<prestamos> prestamos { get; set; }
        public DbSet<proveedor> proveedor { get; set; }
        public DbSet<pto_digitaliza> pto_digitaliza { get; set; }
        public DbSet<pto_usuarios> pto_usuarios { get; set; }
        public DbSet<rango_guia> rango_guia { get; set; }
        public DbSet<recibida> recibida { get; set; }
        public DbSet<recibida_dependencias> recibida_dependencias { get; set; }
        public DbSet<recibida_historial> recibida_historial { get; set; }
        public DbSet<recibida_indices> recibida_indices { get; set; }
        public DbSet<recibida_usuarios> recibida_usuarios { get; set; }
        public DbSet<registro_carpetas> registro_carpetas { get; set; }
        public DbSet<registro_carpetas_indices> registro_carpetas_indices { get; set; }
        public DbSet<registro_estado_despacha> registro_estado_despacha { get; set; }
        public DbSet<respuesta_correspondencia> respuesta_correspondencia { get; set; }
        public DbSet<respuesta_recibida> respuesta_recibida { get; set; }
        public DbSet<respuesta_tramite> respuesta_tramite { get; set; }
        public DbSet<respuesta_tramite_interna> respuesta_tramite_interna { get; set; }
        public DbSet<restore_copia> restore_copia { get; set; }
        public DbSet<sede_cont_courier> sede_cont_courier { get; set; }
        public DbSet<sedes> sedes { get; set; }
        public DbSet<seguimiento_tramite> seguimiento_tramite { get; set; }
        public DbSet<seguimiento_tramite_interna> seguimiento_tramite_interna { get; set; }
        public DbSet<serie_documental> serie_documental { get; set; }
        public DbSet<serv_mens_cont_courier> serv_mens_cont_courier { get; set; }
        public DbSet<servicio_mensajeria> servicio_mensajeria { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tabla_retencion> tabla_retencion { get; set; }
        public DbSet<tabla_valoracion> tabla_valoracion { get; set; }
        public DbSet<temporadas> temporadas { get; set; }
        public DbSet<tipo_documental> tipo_documental { get; set; }
        public DbSet<tipo_documento_correspondencia> tipo_documento_correspondencia { get; set; }
        public DbSet<tipo_documento_parametro> tipo_documento_parametro { get; set; }
        public DbSet<tipo_identificacion_proveedor> tipo_identificacion_proveedor { get; set; }
        public DbSet<tipo_modulo> tipo_modulo { get; set; }
        public DbSet<tipo_trayecto> tipo_trayecto { get; set; }
        public DbSet<tiposenvio> tiposenvio { get; set; }
        public DbSet<tramites_archivo> tramites_archivo { get; set; }
        public DbSet<tramites_responsables> tramites_responsables { get; set; }
        public DbSet<transferencias> transferencias { get; set; }
        public DbSet<unidad_conservacion> unidad_conservacion { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
        public DbSet<usuarios_ldap> usuarios_ldap { get; set; }
        public DbSet<usuarios_ptos> usuarios_ptos { get; set; }
        public DbSet<usuarios_serie> usuarios_serie { get; set; }
        public DbSet<vista> vista { get; set; }
        public DbSet<vista_previa> vista_previa { get; set; }
    
        public virtual ObjectResult<pa_BaseSevenet_Result> pa_BaseSevenet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_BaseSevenet_Result>("pa_BaseSevenet");
        }
    
        public virtual int SearchAllTables(Nullable<int> año)
        {
            var añoParameter = año.HasValue ?
                new ObjectParameter("año", año) :
                new ObjectParameter("año", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SearchAllTables", añoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
