//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificacion
    {
        public notificacion()
        {
            this.item_notificacion = new HashSet<item_notificacion>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public string cuerpo_informe { get; set; }
        public int id_tipo_modulo { get; set; }
    
        public virtual ICollection<item_notificacion> item_notificacion { get; set; }
        public virtual tipo_modulo tipo_modulo { get; set; }
        public virtual tipo_modulo tipo_modulo1 { get; set; }
    }
}
