//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil_campo
    {
        public int id_campo { get; set; }
        public string nombre { get; set; }
        public string login { get; set; }
        public string tipo { get; set; }
        public string defecto { get; set; }
        public string visible { get; set; }
        public string mensaje { get; set; }
        public string shortcut { get; set; }
        public string requerido { get; set; }
        public string valor_defecto { get; set; }
        public string tabla { get; set; }
        public string mostrar_mensaje { get; set; }
        public string listado { get; set; }
        public string cambiar_listado { get; set; }
        public string adicionar_boton_listado { get; set; }
        public string colocar_columna { get; set; }
        public string titulo { get; set; }
        public Nullable<int> posicion { get; set; }
        public Nullable<int> posicion_columna { get; set; }
        public string colocar_sticker { get; set; }
        public Nullable<int> espacio_sticker { get; set; }
        public Nullable<int> posicion_sticker { get; set; }
        public string codigo_barras { get; set; }
        public string campo { get; set; }
        public Nullable<int> espacio_campo { get; set; }
        public Nullable<int> tamano_campo { get; set; }
        public string campo_requerido { get; set; }
        public Nullable<int> posicion_workflow { get; set; }
        public string ident_unico { get; set; }
    }
}
