//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfiles_vista
    {
        public int id { get; set; }
        public string bordes { get; set; }
        public string textonormal { get; set; }
        public string textotitulos { get; set; }
        public string fondobody { get; set; }
        public string botones { get; set; }
        public string entradasform { get; set; }
        public string celdallena { get; set; }
        public string bordestabla { get; set; }
        public string hiperv { get; set; }
        public string hiperv_mueve { get; set; }
        public string chk_llena { get; set; }
        public string imgcorporativo { get; set; }
    }
}
