//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisos_correspondencias
    {
        public int id_tipo_modulo { get; set; }
        public int id_dependencia { get; set; }
        public string login { get; set; }
        public int registrar { get; set; }
        public int modificar { get; set; }
        public int consultar { get; set; }
        public int archivar { get; set; }
        public int guardar { get; set; }
        public int Imprimir { get; set; }
    
        public virtual tipo_modulo tipo_modulo { get; set; }
        public virtual tipo_modulo tipo_modulo1 { get; set; }
    }
}
