//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantilla_usuarios
    {
        public int id_plantilla { get; set; }
        public string login { get; set; }
        public Nullable<int> grabar { get; set; }
        public Nullable<int> imprimir { get; set; }
        public Nullable<int> enviar { get; set; }
    
        public virtual plantilla plantilla { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
