//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class planilla_electro_externa
    {
        public int id_planilla_electro_externa { get; set; }
        public Nullable<int> numero { get; set; }
        public Nullable<int> temporada { get; set; }
        public Nullable<int> id_courier { get; set; }
        public string tipo_servicio { get; set; }
        public Nullable<int> id_sede { get; set; }
        public Nullable<int> id_dependencia { get; set; }
        public string login { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public string hora_envio { get; set; }
        public string observaciones_envio { get; set; }
        public Nullable<int> id_mensajero { get; set; }
        public string estado { get; set; }
    }
}
