//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class planilla_electronica
    {
        public int id_planilla_electronica { get; set; }
        public Nullable<int> numero_planilla { get; set; }
        public Nullable<int> temporada { get; set; }
        public string tipo_comunicacion { get; set; }
        public string precinto { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public Nullable<int> sede_envio { get; set; }
        public Nullable<int> dependencia_envio { get; set; }
        public string login_envio { get; set; }
        public string observaciones_envio { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public Nullable<int> sede_recepcion { get; set; }
        public Nullable<int> dependencia_recepcion { get; set; }
        public string login_recepcion { get; set; }
        public string observaciones_recepcion { get; set; }
        public string hora_envio { get; set; }
        public string hora_recepcion { get; set; }
        public Nullable<int> id_courier { get; set; }
        public string guia { get; set; }
        public Nullable<int> courier_recepcion { get; set; }
        public string estado { get; set; }
    }
}
