//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class prestamos
    {
        public int id_prestamo { get; set; }
        public Nullable<int> id_archivo { get; set; }
        public Nullable<int> dependencia_presta { get; set; }
        public string usuario_presta { get; set; }
        public Nullable<int> dias { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fdevolucion { get; set; }
        public string prestado_a { get; set; }
        public Nullable<System.DateTime> fprestamo { get; set; }
        public Nullable<System.DateTime> fposible { get; set; }
        public string obs_devolucion { get; set; }
        public Nullable<System.DateTime> fgraba { get; set; }
        public Nullable<int> prestado_a_dependencia { get; set; }
        public string archivo_actual { get; set; }
    }
}
