//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        public int id_proveedor { get; set; }
        public string cednit { get; set; }
        public string nombre { get; set; }
        public string observaciones { get; set; }
        public string direccion { get; set; }
        public string telefono_fijo { get; set; }
        public string telefono_celular { get; set; }
        public string email { get; set; }
        public string ciudad { get; set; }
        public string referencia { get; set; }
        public Nullable<int> id_tipo_identifi_proveedor { get; set; }
    }
}
