//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class pto_usuarios
    {
        public pto_usuarios()
        {
            this.plantilla = new HashSet<plantilla>();
        }
    
        public int id_pto { get; set; }
        public string login { get; set; }
        public int id_dependencia { get; set; }
        public Nullable<int> recibida { get; set; }
        public Nullable<int> despachada { get; set; }
        public Nullable<int> interna { get; set; }
        public Nullable<int> digitaliza_docs { get; set; }
        public Nullable<int> digitaliza_carpetas { get; set; }
        public Nullable<int> digitaliza_central { get; set; }
        public Nullable<int> digitaliza_oficina { get; set; }
    
        public virtual pto_digitaliza pto_digitaliza { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual ICollection<plantilla> plantilla { get; set; }
    }
}
