//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class pto_digitaliza
    {
        public pto_digitaliza()
        {
            this.pto_usuarios = new HashSet<pto_usuarios>();
        }
    
        public int id_pto { get; set; }
        public string ruta_carpeta_tmp_cliente { get; set; }
        public string nombre { get; set; }
        public string ruta_carpeta_tmp_servidor { get; set; }
        public string equipo { get; set; }
        public string ip { get; set; }
        public Nullable<int> id_dependencia { get; set; }
        public Nullable<int> adm { get; set; }
        public Nullable<int> linea { get; set; }
    
        public virtual ICollection<pto_usuarios> pto_usuarios { get; set; }
    }
}
