//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class recibida
    {
        public recibida()
        {
            this.control_respuestas = new HashSet<control_respuestas>();
            this.recibida_dependencias = new HashSet<recibida_dependencias>();
            this.recibida_indices = new HashSet<recibida_indices>();
            this.respuesta_tramite = new HashSet<respuesta_tramite>();
            this.seguimiento_tramite = new HashSet<seguimiento_tramite>();
        }
    
        public int id_recibida { get; set; }
        public int consecutivo_fax { get; set; }
        public int consecutivo_email { get; set; }
        public int consecutivo_gral { get; set; }
        public int temporada { get; set; }
        public Nullable<System.DateTime> fgraba { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string id_documento { get; set; }
        public Nullable<int> id_tramite { get; set; }
        public int id_tiposenvio { get; set; }
        public string remitente { get; set; }
        public Nullable<int> n_folios { get; set; }
        public string enviado { get; set; }
        public Nullable<int> estado_tramite { get; set; }
        public string usuario_grabo { get; set; }
        public string cd { get; set; }
        public Nullable<int> sizea { get; set; }
        public string id_ciudad { get; set; }
        public string resumen { get; set; }
        public Nullable<System.DateTime> fradica { get; set; }
        public string hradica { get; set; }
        public Nullable<int> id_flujo { get; set; }
        public Nullable<int> id_doc { get; set; }
        public string anexos { get; set; }
        public Nullable<int> id_serie { get; set; }
        public Nullable<int> id_dependencia { get; set; }
        public byte[] imagen { get; set; }
        public Nullable<int> id_sede { get; set; }
        public Nullable<int> id_mensajero { get; set; }
        public Nullable<int> estado { get; set; }
        public string archivo { get; set; }
        public Nullable<int> imagenes { get; set; }
        public string responsable { get; set; }
        public Nullable<int> longitud { get; set; }
        public string ext { get; set; }
        public string persona_firma { get; set; }
        public string tipo_documento { get; set; }
        public string referencia { get; set; }
        public string guia { get; set; }
        public Nullable<int> ubicacion_fisica { get; set; }
        public string estado_ubicacion { get; set; }
        public string estado_correspondencia { get; set; }
        public Nullable<int> id_dependencia_radicacion { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public string remitente_cednit { get; set; }
        public string remitente_nombre { get; set; }
        public string remitente_observaciones { get; set; }
        public string remitente_direccion { get; set; }
        public string remitente_telefono_fijo { get; set; }
        public string remitente_telefono_celular { get; set; }
        public string remitente_email { get; set; }
        public string remitente_ciudad { get; set; }
        public string remitente_referencia { get; set; }
        public string ruta_imagen { get; set; }
        public string encriptada { get; set; }
        public Nullable<System.DateTime> fecha_limite_tramite { get; set; }
        public Nullable<int> id_archivo { get; set; }
        public Nullable<System.DateTime> fmodifica { get; set; }
        public Nullable<int> remi_id_tipo_iden_proveedor { get; set; }
    
        public virtual ICollection<control_respuestas> control_respuestas { get; set; }
        public virtual ICollection<recibida_dependencias> recibida_dependencias { get; set; }
        public virtual ICollection<recibida_indices> recibida_indices { get; set; }
        public virtual temporadas temporadas { get; set; }
        public virtual ICollection<respuesta_tramite> respuesta_tramite { get; set; }
        public virtual ICollection<seguimiento_tramite> seguimiento_tramite { get; set; }
    }
}
