//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro_carpetas
    {
        public registro_carpetas()
        {
            this.anexo = new HashSet<anexo>();
            this.campo_carpeta = new HashSet<campo_carpeta>();
            this.registro_carpetas_indices = new HashSet<registro_carpetas_indices>();
        }
    
        public int id_registro_carpetas { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public string orden { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> f_inicial { get; set; }
        public Nullable<System.DateTime> f_final { get; set; }
        public string unidad_conservacion { get; set; }
        public Nullable<int> n_folios { get; set; }
        public string ubicacion { get; set; }
        public string notas { get; set; }
        public string carpeta { get; set; }
        public Nullable<int> transferido { get; set; }
        public string deposito { get; set; }
        public string gaveta { get; set; }
        public string bandeja { get; set; }
        public string caja_estante { get; set; }
        public string caja { get; set; }
        public Nullable<int> rango1 { get; set; }
        public Nullable<int> rango2 { get; set; }
        public Nullable<System.DateTime> fgraba { get; set; }
        public string cor { get; set; }
    
        public virtual ICollection<anexo> anexo { get; set; }
        public virtual ICollection<campo_carpeta> campo_carpeta { get; set; }
        public virtual categorias categorias { get; set; }
        public virtual ICollection<registro_carpetas_indices> registro_carpetas_indices { get; set; }
    }
}
