//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class respuesta_correspondencia
    {
        public int id { get; set; }
        public string tipo_correspondencia { get; set; }
        public int id_correspondencia { get; set; }
        public string tipo_correspondencia_ref { get; set; }
        public int id_correspondencia_ref { get; set; }
        public Nullable<int> id_tramite { get; set; }
        public string estado_tramite { get; set; }
    }
}
