//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class serie_documental
    {
        public serie_documental()
        {
            this.inventario_documental = new HashSet<inventario_documental>();
            this.tabla_retencion = new HashSet<tabla_retencion>();
            this.tipo_documental = new HashSet<tipo_documental>();
            this.usuarios_serie = new HashSet<usuarios_serie>();
        }
    
        public int id_seriedocumental { get; set; }
        public int serie_padre { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> tradicion_documental { get; set; }
        public Nullable<int> tiempo_gestion { get; set; }
        public Nullable<int> tiempo_central { get; set; }
        public Nullable<int> conservacion_total { get; set; }
        public Nullable<int> micro_digitaliza { get; set; }
        public Nullable<int> seleccion { get; set; }
        public Nullable<int> eliminacion { get; set; }
        public string procedimiento { get; set; }
        public Nullable<int> papel { get; set; }
        public Nullable<int> electronico { get; set; }
    
        public virtual ICollection<inventario_documental> inventario_documental { get; set; }
        public virtual ICollection<tabla_retencion> tabla_retencion { get; set; }
        public virtual ICollection<tipo_documental> tipo_documental { get; set; }
        public virtual ICollection<usuarios_serie> usuarios_serie { get; set; }
    }
}
