//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class serv_mens_cont_courier
    {
        public int id_serv_mens_cont_courier { get; set; }
        public Nullable<int> id_servicio_mensajeria { get; set; }
        public Nullable<int> id_sede_cont_courier { get; set; }
        public string manejo_guia { get; set; }
        public string observaciones { get; set; }
        public string estado { get; set; }
    }
}
