//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_retencion
    {
        public int id_tabla { get; set; }
        public Nullable<int> id_dependencia { get; set; }
        public Nullable<int> id_seriedocumental { get; set; }
    
        public virtual dependencias dependencias { get; set; }
        public virtual serie_documental serie_documental { get; set; }
    }
}
