//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class temporadas
    {
        public temporadas()
        {
            this.despachada = new HashSet<despachada>();
            this.interna = new HashSet<interna>();
            this.recibida = new HashSet<recibida>();
        }
    
        public int temporada { get; set; }
        public string carpeta { get; set; }
    
        public virtual ICollection<despachada> despachada { get; set; }
        public virtual ICollection<interna> interna { get; set; }
        public virtual ICollection<recibida> recibida { get; set; }
    }
}
