//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_documento_parametro
    {
        public string tipo_correspondencia { get; set; }
        public string tipo_documento { get; set; }
        public string parametro { get; set; }
        public string valor_parametro { get; set; }
    }
}
