//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios_serie
    {
        public string login { get; set; }
        public int id_seriedocumental { get; set; }
        public int id_dependencia { get; set; }
        public int id_doce { get; set; }
        public Nullable<int> grabar { get; set; }
        public Nullable<int> imprimir { get; set; }
        public Nullable<int> registrar { get; set; }
        public Nullable<int> enviar { get; set; }
    
        public virtual dependencias dependencias { get; set; }
        public virtual serie_documental serie_documental { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
