//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios_ldap
    {
        public string login { get; set; }
        public string pass { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_dependencia { get; set; }
        public Nullable<int> id_cargos { get; set; }
        public Nullable<int> id_sede { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fecha_grab { get; set; }
        public string estado { get; set; }
    }
}
