//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public usuarios()
        {
            this.anotaciones = new HashSet<anotaciones>();
            this.categorias_usuarios = new HashSet<categorias_usuarios>();
            this.control_respuestas = new HashSet<control_respuestas>();
            this.despachada_dependencias = new HashSet<despachada_dependencias>();
            this.interna_dependencias = new HashSet<interna_dependencias>();
            this.plantilla_usuarios = new HashSet<plantilla_usuarios>();
            this.pto_usuarios = new HashSet<pto_usuarios>();
            this.recibida_dependencias = new HashSet<recibida_dependencias>();
            this.usuarios_serie = new HashSet<usuarios_serie>();
            this.dependencias1 = new HashSet<dependencias>();
        }
    
        public string login { get; set; }
        public string pass { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_dependencia { get; set; }
        public Nullable<int> id_cargos { get; set; }
        public Nullable<int> id_sede { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<System.DateTime> fecha_grab { get; set; }
        public string foto { get; set; }
        public Nullable<decimal> publica_foto { get; set; }
        public string cuota { get; set; }
        public Nullable<decimal> activar { get; set; }
        public Nullable<decimal> webmail { get; set; }
        public string passwd_correo { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<anotaciones> anotaciones { get; set; }
        public virtual ICollection<categorias_usuarios> categorias_usuarios { get; set; }
        public virtual central_usuarios central_usuarios { get; set; }
        public virtual ICollection<control_respuestas> control_respuestas { get; set; }
        public virtual dependencias dependencias { get; set; }
        public virtual ICollection<despachada_dependencias> despachada_dependencias { get; set; }
        public virtual flujo_responsables flujo_responsables { get; set; }
        public virtual ICollection<interna_dependencias> interna_dependencias { get; set; }
        public virtual ICollection<plantilla_usuarios> plantilla_usuarios { get; set; }
        public virtual ICollection<pto_usuarios> pto_usuarios { get; set; }
        public virtual ICollection<recibida_dependencias> recibida_dependencias { get; set; }
        public virtual ICollection<usuarios_serie> usuarios_serie { get; set; }
        public virtual ICollection<dependencias> dependencias1 { get; set; }
    }
}
