//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosActasActivos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vista
    {
        public int id_vista { get; set; }
        public int id_externo { get; set; }
        public string tabla_externo { get; set; }
        public Nullable<int> id_padre { get; set; }
        public Nullable<int> id_dependencia { get; set; }
        public string creador { get; set; }
    }
}
